name: "[tester] CI for tests"

on:
  pull_request:
    branches:
      - "master"
    paths:
      - "src/**"
      - "Dockerfile"
      - "docker-entrypoint.sh"
  push:
    branches:
      - "*"
      - "!main"
    paths:
      - "src/**"
      - "Dockerfile"
      - "docker-entrypoint.sh"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build dockerfile (without push)
        run: |
          docker buildx build \
          --platform=linux/amd64,linux/arm/v7,linux/arm64 \
          --output "type=image,push=false" \
          --file ./Dockerfile .
